name: ci-s002

on:
  pull_request:
    paths:
      - ".github/workflows/ci-s002.yml"
      - "secuencia/s002/**"
      - "!secuencia/s002/script/**"
      - "!secuencia/s002/ejemplos/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci-s002.yml"
      - "secuencia/s002/**"
      - "!secuencia/s002/script/**"
      - "!secuencia/s002/ejemplos/**"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: secuencia/s002
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements-dev.txt
      - run: pre-commit run --all-files
      - run: pytest
      - run: python -m pdoc doevc_s002 -o site
